// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBroodDbVersionCtl = "brood_db_version_ctl"

// BroodDbVersionCtl mapped from table <brood_db_version_ctl>
type BroodDbVersionCtl struct {
	ID              int64  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`                       // 数据库版本ID
	BusinessSpace   string `gorm:"column:business_space;type:varchar(50);not null" json:"business_space"`                     // 业务空间
	MajorVersion    int64  `gorm:"column:major_version;type:int;not null" json:"major_version"`                               // 主版本号
	MinorVersion    int64  `gorm:"column:minor_version;type:int;not null" json:"minor_version"`                               // 次版本号
	PatchVersion    int64  `gorm:"column:patch_version;type:int;not null" json:"patch_version"`                               // 补丁版本号
	ExtendVersion   int64  `gorm:"column:extend_version;type:int;not null" json:"extend_version"`                             // 扩展版本号
	Version         string `gorm:"column:version;type:varchar(50);not null" json:"version"`                                   // 版本号,V[major].[minor].[patch].[extend_version]
	CustomName      string `gorm:"column:custom_name;type:varchar(50);not null;default:none" json:"custom_name"`              // 脚本自定义名称
	VersionType     string `gorm:"column:version_type;type:varchar(10);not null" json:"version_type"`                         // 版本类型:SQL/BaseLine
	ScriptFileName  string `gorm:"column:script_file_name;type:varchar(200);not null;default:none" json:"script_file_name"`   // 脚本文件名
	ScriptDigestHex string `gorm:"column:script_digest_hex;type:varchar(200);not null;default:none" json:"script_digest_hex"` // 脚本内容摘要(16进制)
	Success         int64  `gorm:"column:success;type:tinyint;not null" json:"success"`                                       // 是否执行成功
	ExecutionTime   int64  `gorm:"column:execution_time;type:int;not null" json:"execution_time"`                             // 脚本安装耗时
	InstallTime     string `gorm:"column:install_time;type:varchar(19);not null" json:"install_time"`                         // 脚本安装时间,格式:[yyyy-MM-dd HH:mm:ss]
	InstallUser     string `gorm:"column:install_user;type:varchar(100);not null" json:"install_user"`                        // 脚本安装用户
}

// TableName BroodDbVersionCtl's table name
func (*BroodDbVersionCtl) TableName() string {
	return TableNameBroodDbVersionCtl
}
